const express = require('express');
const router = express.Router();
const auth = require('../middleware/auth');
const Blog = require('../models/Blog');
const mongoose = require('mongoose');

// GET all blogs with pagination
router.get('/', async (req, res) => {
  try {
    const page = parseInt(req.query.page) || 1;
    const limit = parseInt(req.query.limit) || 10;
    const skip = (page - 1) * limit;

    const blogs = await Blog.find()
      .select('title slug summary date images seoTitle seoMetaDescription faqs') // Added faqs to selection
      .sort({ date: -1 })
      .skip(skip)
      .limit(limit)
      .populate('faqs', 'question answer order') // Populate FAQ basic info
      .lean();

    const total = await Blog.countDocuments();

    res.json({
      blogs,
      currentPage: page,
      totalPages: Math.ceil(total / limit),
      totalBlogs: total,
    });
  } catch (err) {
    console.error('Blog fetch error:', err);
    res.status(500).json({ msg: 'Server error', error: err.message });
  }
});

// GET single blog - SUPPORTS BOTH ID AND SLUG (WITH FAQ POPULATION)
router.get('/:identifier', async (req, res) => {
  try {
    const identifier = req.params.identifier;
    let blog;
    
    // Check if identifier is a valid MongoDB ObjectId
    const isValidObjectId = mongoose.Types.ObjectId.isValid(identifier);
    
    if (isValidObjectId) {
      // Try to fetch by ID first
      blog = await Blog.findById(identifier)
        .populate('faqs', 'question answer order isActive') // Populate full FAQ data
        .lean();
    } else {
      // If not valid ObjectId, fetch by slug
      blog = await Blog.findOne({ slug: identifier })
        .populate('faqs', 'question answer order isActive') // Populate full FAQ data
        .lean();
    }
    
    if (!blog) return res.status(404).json({ msg: 'Blog not found' });
    
    // Filter only active FAQs
    if (blog.faqs) {
      blog.faqs = blog.faqs.filter(faq => faq.isActive !== false);
    }
    
    res.set('Cache-Control', 'public, max-age=300');
    res.json(blog);
  } catch (err) {
    console.error(err.message);
    res.status(500).json({ msg: 'Server error' });
  }
});

// CREATE blog (WITH FAQ SUPPORT)
router.post('/', auth, async (req, res) => {
  try {
    const { 
      title, 
      summary, 
      content, 
      images = [], 
      date, 
      seoFocusKeyword, 
      seoTitle, 
      seoMetaDescription,
      faqs = [] // Added FAQs array
    } = req.body;

    const blog = new Blog({
      title,
      summary,
      content,
      images,
      date: date ? new Date(date) : new Date(),
      seoFocusKeyword,
      seoTitle,
      seoMetaDescription,
      faqs, // Add FAQs to the blog
      // slug will be auto-generated by the pre-save middleware
    });

    await blog.save();
    
    // Populate FAQs before sending response
    await blog.populate('faqs', 'question answer order');
    
    res.status(201).json(blog);
  } catch (err) {
    console.error('Blog create error:', err);
    res.status(500).json({ msg: 'Server error', error: err.message });
  }
});

// UPDATE blog (WITH FAQ SUPPORT)
router.put('/:id', auth, async (req, res) => {
  try {
    const { 
      title, 
      summary, 
      content, 
      images = [], 
      date, 
      seoFocusKeyword, 
      seoTitle, 
      seoMetaDescription,
      faqs = [] // Added FAQs array
    } = req.body;

    const existingBlog = await Blog.findById(req.params.id);
    if (!existingBlog) return res.status(404).json({ msg: 'Blog not found' });

    const updateData = {
      title,
      summary,
      content,
      images: images.slice(0, 5),
      date: date ? new Date(date) : new Date(),
      seoFocusKeyword,
      seoTitle,
      seoMetaDescription,
      faqs, // Update FAQs
    };

    const blog = await Blog.findByIdAndUpdate(
      req.params.id,
      updateData,
      { new: true, runValidators: true }
    ).populate('faqs', 'question answer order isActive'); // Populate FAQs in response

    console.log('✅ Blog updated:', blog._id, 'Images count:', blog.images.length, 'FAQs count:', blog.faqs?.length);
    res.json(blog);
  } catch (err) {
    console.error('Blog update error:', err);
    res.status(500).json({ msg: 'Server error', error: err.message });
  }
});

// DELETE blog
router.delete('/:id', auth, async (req, res) => {
  try {
    const blog = await Blog.findByIdAndDelete(req.params.id);
    if (!blog) return res.status(404).json({ msg: 'Blog not found' });
    res.json({ msg: 'Blog deleted' });
  } catch (err) {
    console.error(err);
    res.status(500).json({ msg: 'Server error' });
  }
});

module.exports = router;